'use client';

import { useState } from 'react';
import { AlertCircle, Bot, RefreshCw, Sparkles } from 'lucide-react';
import { Badge, Button, Card, CardHeader, Spinner } from '@/components/ui';
import { useApi } from '@/lib/useApi';
import { fetcher } from '@/lib/fetcher';

type Brief = {
  summary: string;
  score: number;
  factors: string[];
  source: 'groq' | 'seed';
  model: string;
  generatedAt: string;
};

type AiState = { configured: boolean; brief: Brief | null };

function scoreTone(score: number): 'green' | 'amber' | 'red' {
  if (score >= 70) return 'green';
  if (score >= 40) return 'amber';
  return 'red';
}

/**
 * Optional AI brief for a lead, backed by Groq.
 *
 * The whole feature is optional: with no GROQ_API_KEY the endpoint reports
 * `configured: false` and this renders an explicit setup note rather than a
 * button that would fail. A brief seeded into the lead's metadata is shown
 * either way, clearly labelled as seeded so it is never mistaken for a live
 * model response.
 */
export default function LeadAiPanel({ leadId }: { leadId: string }) {
  const { data, error, loading, reload } = useApi<AiState>(`/api/leads/${leadId}/ai`, { deps: [leadId] });
  const [busy, setBusy] = useState(false);
  const [fail, setFail] = useState<string | null>(null);

  const generate = async () => {
    setBusy(true);
    setFail(null);
    try {
      await fetcher(`/api/leads/${leadId}/ai`, { method: 'POST' });
      await reload();
    } catch (e) {
      setFail((e as Error).message);
    } finally {
      setBusy(false);
    }
  };

  if (loading && !data) {
    return (
      <Card>
        <CardHeader title="AI brief" />
        <div className="flex justify-center p-6"><Spinner /></div>
      </Card>
    );
  }

  if (error && !data) {
    return (
      <Card>
        <CardHeader title="AI brief" />
        <p className="flex items-start gap-2 text-sm text-ink-muted">
          <AlertCircle size={16} className="mt-0.5 shrink-0" />
          Could not load the AI brief.
        </p>
      </Card>
    );
  }

  const brief = data?.brief ?? null;
  const configured = data?.configured ?? false;

  return (
    <Card>
      <CardHeader
        title={
          <span className="flex items-center gap-2">
            <Bot size={18} className="text-primary-600" />
            AI brief
          </span>
        }
        subtitle={brief?.source === 'groq' ? `Generated by ${brief.model}` : undefined}
        action={
          configured ? (
            <Button
              variant="secondary"
              className="!py-1.5"
              onClick={generate}
              loading={busy}
              aria-label={brief ? 'Regenerate AI brief' : 'Generate AI brief'}
            >
              {brief ? <RefreshCw size={14} /> : <Sparkles size={14} />}
              {brief ? 'Regenerate' : 'Generate'}
            </Button>
          ) : undefined
        }
      />

      {!configured && (
        <p className="mb-4 rounded-xl bg-clay-deep px-4 py-3 text-sm text-ink-muted shadow-clay-inset-sm">
          AI is not configured on this server. Set <code className="font-semibold text-ink">GROQ_API_KEY</code>{' '}
          (and optionally <code className="font-semibold text-ink">GROQ_MODEL</code>) to enable generation.
        </p>
      )}

      {!brief ? (
        !configured && (
          <p className="text-sm text-ink-faint">
            No brief has been generated for this lead yet.
          </p>
        )
      ) : (
        <div className="space-y-4">
          <div className="flex items-center gap-4">
            <div
              className="flex h-16 w-16 shrink-0 flex-col items-center justify-center rounded-2xl bg-surface shadow-clay-inset-sm"
              aria-label={`Intent score ${brief.score} out of 100`}
            >
              <span className="text-2xl font-bold tabular-nums text-ink">{brief.score}</span>
              <span className="text-[10px] font-semibold uppercase tracking-wider text-ink-faint">score</span>
            </div>
            <div className="min-w-0 flex-1">
              <Badge tone={scoreTone(brief.score)}>
                {brief.score >= 70 ? 'High intent' : brief.score >= 40 ? 'Warm' : 'Low intent'}
              </Badge>
              {brief.source === 'seed' && (
                <Badge tone="gray" className="ml-1.5">Sample data</Badge>
              )}
            </div>
          </div>

          <p className="text-sm leading-relaxed text-ink">{brief.summary}</p>

          {brief.factors.length > 0 && (
            <ul className="space-y-1.5">
              {brief.factors.map((f, i) => (
                <li key={i} className="flex gap-2 text-sm text-ink-muted">
                  <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-primary-400" aria-hidden />
                  {f}
                </li>
              ))}
            </ul>
          )}

          {brief.generatedAt && (
            <p className="text-xs text-ink-faint">
              Updated {new Date(brief.generatedAt).toLocaleString('en-IN')}
            </p>
          )}
        </div>
      )}

      {fail && (
        <p role="alert" className="mt-4 rounded-xl bg-rose-100 px-4 py-3 text-sm font-medium text-rose-800 shadow-clay-inset-sm">
          {fail}
        </p>
      )}
    </Card>
  );
}
